numpy and vectorization

In [1]:
import numpy as np
import time

In [24]:
array_a = np.zeros((4, 2), dtype=float)
array_b = np.zeros(4)
array_c = np.random.random_sample(4)
print(f"array_c dtype {array_c.dtype},array_c shape is {array_c.shape}")
array_d = np.arange(4)
array_e = np.random.rand(4) * 10
array_f = np.array([1, 2, 3, 4]);
print(f"np.array([5.,4,3,2]): a = {array_f}, a shape = {array_f.shape}, a data type = {array_f.dtype}")  # this is int64
array_g = np.array([5., 4, 3, 2]);
print(
    f"np.array([5.,4,3,2]): a = {array_g}, a shape = {array_g.shape}, a data type = {array_g.dtype}")  # this is float64

array_c dtype float64,array_c shape is (4,)
np.array([5.,4,3,2]): a = [1 2 3 4], a shape = (4,), a data type = int64
np.array([5.,4,3,2]): a = [5. 4. 3. 2.], a shape = (4,), a data type = float64


In [28]:
array_example = np.arange(10)
print(array_example)
print(f"array_example[2] shape {array_example[2].shape} array_example = {array_example[2]}")
try:
    c = array_example[10]
except Exception as e:
    print("The errors is coming")
    print(e)

[0 1 2 3 4 5 6 7 8 9]
array_example[2] shape () array_example = 2
The errors is coming
index 10 is out of bounds for axis 0 with size 10


In [33]:
array_example = np.arange(10)
print(array_example)
c = array_example[2:7:1]
c = array_example[2:7:2]
c = array_example[3:]
c = array_example[:7]
c = array_example[:]
c

[0 1 2 3 4 5 6 7 8 9]


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [36]:
array_example = np.arange(10)
print(array_example)
b = -array_example
print(f"b = -array_example {b}")
b = np.sum(array_example)
b = np.mean(array_example)
b = array_example ** 2
b

[0 1 2 3 4 5 6 7 8 9]
b = -array_example [ 0 -1 -2 -3 -4 -5 -6 -7 -8 -9]


array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [39]:
array1 = np.array([1, 2, 3, 4])
array2 = np.array([5, 6, 7, 8])

result = np.dot(array1, array2)
result

70

In [43]:
np.random.seed(1)
a = np.random.rand(100000)
b = np.random.rand(100000)
tic = time.time()
c = np.dot(a,b)
toc = time.time()
print((toc - tic) * 1000)

0.12493133544921875


In [47]:
a = np.arange(6).reshape(-1,2)
a.shape

(3, 2)